"""
Defines a tool for viewing the Python Abstract Syntax Tree (AST) generated by
an input block of code.
"""

#-------------------------------------------------------------------------------
#  License: See section (A) of the .../facets/LICENSE.txt file.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#  Imports:
#-------------------------------------------------------------------------------

from facets.api \
    import Str, Bool, View, VGroup, Item, UItem, ASTEditor, SyncValue

from tools \
    import Tool

#-------------------------------------------------------------------------------
#  'ASTViewer' class:
#-------------------------------------------------------------------------------

class ASTViewer ( Tool ):

    #-- Facet Definitions ------------------------------------------------------

    # The name of the tool:
    name = 'AST Viewer'

    # Should AST nodes be automatically opened?
    auto_open = Bool( True, save_state = True )

    # The Python code whose AST is to be viewed:
    code = Str( connect = 'to: Python source code' )

    #-- Facets View Definitions ------------------------------------------------

    def default_facets_view ( self ):
        return View(
            UItem( 'code',
                   editor = ASTEditor(
                       auto_open = SyncValue( self, 'auto_open' )
                   )
            )
        )


    options = View(
        VGroup(
            Item( 'auto_open', label = 'Automatically open AST nodes' ),
            group_theme = '#themes:tool_options_group'
        )
    )

#-- EOF ------------------------------------------------------------------------
