"""
Defines the FileMonitor tool.
"""

#-------------------------------------------------------------------------------
#  License: See sections (A) and (B) of the .../facets/LICENSE.txt file.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#  Imports:
#-------------------------------------------------------------------------------

import logging

from os.path \
    import split, splitext, isfile

from facets.api \
    import HasPrivateFacets, Str, List, Instance, Directory, Enum, View, \
           VGroup, Tabbed, VGroup, HGroup, Item, GridEditor, InstanceEditor

from facets.core.facet_base \
    import read_file

from facets.extra.api \
    import import_symbol, file_watch

from tools \
    import Tool


logger = logging.getLogger( __name__ )


#-------------------------------------------------------------------------------
#  Facet definitions:
#-------------------------------------------------------------------------------

LogMode = Enum( 'Ignore', 'Print', 'Log' )

#-------------------------------------------------------------------------------
#  Helper Functions:
#-------------------------------------------------------------------------------

def get_args ( *args, **kw ):
    """ Returns the input arguments and keyword arguments.
    """
    return ( args, kw )

#-------------------------------------------------------------------------------
#  'Rule' class:
#-------------------------------------------------------------------------------

class Rule ( HasPrivateFacets ):

    #-- Facet Definitions ------------------------------------------------------

    # The owner of the Rule:
    owner = Instance( 'FileMonitor' )

    # The name of the rule:
    name = Str

    # The file extension the rule applies to:
    extension = Str

    # The rule to be applied:
    rule = Str

    #-- Public Methods ---------------------------------------------------------

    def apply ( self, file_name, monitor ):
        """ Applies the rule to a specified file for a specified Monitor.
        """
        extension = self.extension.strip()
        if file_name[ -len( extension ): ] == extension:
            self.invoke( file_name, monitor )


    def invoke ( self, file_name, monitor ):
        """ Invokes the rule for a specified file name.
        """
        path, base = split( file_name )
        root, ext  = splitext( base )
        dic = {
            '%n': repr( file_name ),
            '%p': repr( path ),
            '%b': repr( base ),
            '%r': repr( root ),
            '%x': repr( ext ),
            '%^': repr( monitor.path ),
            '%.': repr( join( path, root ) ),
            '%m': 'monitor'
        }
        if '%c' in rule:
            dic[ '%c' ] = repr( read_file( file_name ) )

        monitor.invoke( file_name, self.substitute( rule, dic ) )


    def substitute ( self, rule, dic ):
        """ Substitutes the various macros in a dictionary into a specified
            rule.
        """
        for name, value in dic.items():
            rule = rule.replace( name, repr( value ) )

        return rule

#-------------------------------------------------------------------------------
#  'RuleSet' class:
#-------------------------------------------------------------------------------

class RuleSet ( HasPrivateFacets ):

    #-- Facet Definitions ------------------------------------------------------

    # The owner of the RuleSet:
    owner = Instance( 'FileMonitor' )

    # The name of the rule set:
    name = Str

    # The set of rules:
    rules = List( Rule )

    #-- Public Methods ---------------------------------------------------------

    def apply ( self, file_name, monitor ):
        """ Applies the rule set to a specified file for a specified Monitor.
        """
        for rule in self.rules:
            rule.apply( file_name, monitor )

#-------------------------------------------------------------------------------
#  'Monitor' class:
#-------------------------------------------------------------------------------

class Monitor ( HasPrivateFacets ):

    #-- Facet Definitions ------------------------------------------------------

    # The owner of the Monitor:
    owner = Instance( 'FileMonitor' )

    # The path to be monitored:
    path = Directory

    # Should sub-directories be included?
    recursive = Bool( False )

    # The rule set to apply to the monitored path:
    rule_set = Instance( RuleSet )

    # The set of available RuleSets:
    rule_sets = Property

    # Is the monitor enabled?
    enabled = Bool( True )

    # Logging mode for information generated by rules:
    rule_log_mode = LogMode

    # Logging mode for information generated by rule processor functions:
    function_log_mode = LogMode

    #-- Facets View Definitions ------------------------------------------------

    facets_view = View(
        HGroup(
            Item( 'path',
                  width = -200
            ),
            Item( 'recursive',
                  label = 'Include subdirectories'
            ),
        ),
        HGroup(
            Item( 'rule_log_mode',
                  label = 'Log mode for rules'
            ),
            Item( 'function_log_mode',
                  label = 'Log mode for functions'
            )
        ),
        Item( 'rule_set',
              label = 'Rule Set',
              editor = InstanceEditor( name = 'rule_sets' ),
        ),
        Item( 'enabled' )
    )

    #-- Public Methods ---------------------------------------------------------

    def activate ( self ):
        """ Activates the monitor.
        """
        if self.enabled:
            self.start_monitoring()


    def start_monitoring ( self ):
        """ Starts monitoring the associated path for file changes.
        """
        file_watch.watch( self._file_set, self.path )


    def deactivate ( self ):
        """ Deactivates the monitor.
        """
        if self.enabled:
            self.stop_monitoring()


    def stop_monitoring ( self ):
        """ Stops monitoring the associated path for file changes.
        """
        file_watch.watch( self._file_set, self.path, remove = True )


    def invoke ( self, file_name, rule ):
        """ Invokes a specified rule.
        """
        rlm = self.rule_log_mode
        self.log( "%s changed" % file_name, rlm )

        left = rule.find( '(' )
        if left < 0:
            self.log( 'Invalid syntax for rule:' % rule, rlm )
            return

        result = None
        equal  = rule.find( '=' )
        if equal >= 0:
            if equal < left:
                result = rule[ : equal ].strip()
                rule   = rule[ equal + 1: ].strip()
                left   = rule.find( '(' )
        function_name = rule[ : left ].strip()
        dot = function.find( '.' )
        if dot < 0:
            function_name = '%s.%s.%s' % ( self.owner.import_path,
                                           function_name, function_name )
        function = import_symbol( function_name )
        if function is None:
            self.log( 'Could not find function: ' + function_name, rlm )
            return

        params = rule[ left: ]
        try:
            args, kw = eval( 'get_args' + params )
        except:
            self.log( 'Syntax error in argument list: ' + params, rlm )
            return

        self.log( 'Applying rule: %s' % rule, rlm )

        data = function( *args, **kw )

        if ( result is not None ) and ( data is not None ):
            fh = None
            try:
                fh = file( result, 'wb' )
                fh.write( data )
                fh.close()
                self.log( 'Wrote result to: ' + result, rlm )
            except:
                self.log( 'Error writing result to: ' + result, rlm )
                if fh is not None:
                    try:
                        fh.close()
                    except:
                        pass


    def log ( self, msg, log_mode = None ):
        """ Logs a specified message using a specified log mode.
        """
        if log_mode is None:
            log_mode = self.rule_log_mode

        if log_mode == 'Print':
            print msg

        elif log_mode == 'Log':
            logger.Info( msg )


    def set_owner_listeners ( self, object, remove ):
        """ Sets/Resets the listeners on the object's 'owner'.
        """
        if object is not None:
            object.on_facet_set( self._rule_sets_set, 'rule_sets',
                                 remove = remove )
            object.on_facet_set( self._rule_sets_set, 'rule_sets_items',
                                 remove = remove )

    #-- Property Implementations -----------------------------------------------

    def _get_rule_sets ( self ):
        return self.owner.rule_sets

    #-- Facet Event Handlers ---------------------------------------------------

    def _enabled_set ( self, enabled ):
        """ Handles the 'enabled' facet being changed.
        """
        if enabled:
            self.start_monitoring()
        else:
            self.stop_monitoring()


    def _file_set ( self, file_name ):
        """ Handles a monitored file being changed.
        """
        if isfile( file_name ):
            self.rule_set.apply( file_name, self )


    def _owner_set ( self, old, new ):
        """ Handles the 'owner' facet being changed.
        """
        self.set_owner_listeners( old, True )
        self.set_owner_listeners( new, False )


    def _rule_sets_set ( self ):
        """ Handles the owner's 'rule_sets' being changed.
        """
        self.facet_property_set( 'rule_sets', [ ], self.rule_sets )

#-------------------------------------------------------------------------------
#  Defines the FileMonitor grid editors:
#-------------------------------------------------------------------------------

monitor_grid_editor = GridEditor()

rule_set_grid_editor = GridEditor()

rules_grid_editor = GridEditor()

#-------------------------------------------------------------------------------
#  'FileMonitor' tool:
#-------------------------------------------------------------------------------

class FileMonitor ( Tool ):

    #-- Facet Definitions ------------------------------------------------------

    # The name of the tool:
    name = 'File Monitor'

    # The set of currently defined monitors:
    monitors = List( Monitor, save_state = True )

    # The set of currently defined rules sets:
    rule_sets = List( RuleSet, save_state = True )

    # The set of currently defined rules:
    rules = List( Rule, save_state = True )

    # Default path to import file monitor functions from:
    import_path = Str( 'facets.extra.tools.file_monitor_functions',
                       save_state = True )

    #-- Facets View Definitions ------------------------------------------------

    facets_view = View(
        Tabbed(
            VGroup(
                Item( 'monitors',
                      show_label = False,
                      editor     = monitor_grid_editor
                ),
                label = 'Monitors'
            ),
            VGroup(
                Item( 'rule_sets',
                      show_label = False,
                      editor     = rule_sets_grid_editor
                ),
                label = 'Rule Sets'
            ),
            VGroup(
                Item( 'rules',
                      show_label = False,
                      editor     = rules_grid_editor
                ),
                label = 'Rules'
            ),
            id = 'tabbed'
        )
    )

    options = View(
        VGroup(
            Item( 'import_path',
                  label = 'Default import path',
                  width = -200
            ),
            group_theme = '#themes:tool_options_group'
        )
    )

    #-- Facet Event Handlers ---------------------------------------------------

    def _monitors_set ( self, old, new ):
        """ Handles the 'monitors' facet being changed.
        """
        for monitor in old:
            monitor.owner = None
            monitor.activate()

        for monitor in new:
            monitor.owner = self
            monitor.deactivate()


    def _monitors_items_set ( self, event ):
        for monitor in event.removed:
            monitor.owner = None
            monitor.deactivate()

        for monitor in event.added:
            monitor.owner = self
            monitor.activate()


    def _rule_sets_set ( self, old, new ):
        """ Handles the 'rule_sets' facet being changed.
        """
        for rule_set in old:
            rule_set.owner = None

        for rule_set in new:
            rule_set.owner = self


    def _rule_sets_items_set ( self, event ):
        """ Handles the 'rule_sets' facet being changed.
        """
        for rule_set in event.removed:
            rule_set.owner = None

        for rule_set in event.added:
            rule_set.owner = self


    def _rules_set ( self, old, new ):
        """ Handles the 'rules' facet being changed.
        """
        for rule in old:
            rule.owner = None

        for rule in new:
            rule.owner = self


    def _rules_items_set ( self, event ):
        """ Handles the 'rules' facet being changed.
        """
        for rule in event.removed:
            rule.owner = None

        for rule in event.added:
            rule.owner = self

#-- EOF ------------------------------------------------------------------------